"""Add server ip column to tenant

Revision ID: 1caef18bcb8c
Revises: f260d9d87ad0
Create Date: 2025-06-15 17:26:35.539382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1caef18bcb8c'
down_revision: Union[str, None] = 'f260d9d87ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('server_id', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'server_id')
    # ### end Alembic commands ###
