"""Rename server id column

Revision ID: 22f02c240db8
Revises: 1caef18bcb8c
Create Date: 2025-06-22 02:43:34.598080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f02c240db8'
down_revision: Union[str, None] = '1caef18bcb8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('server_ip', sa.String(length=15), nullable=True))
    op.drop_column('tenants', 'server_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('server_id', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_column('tenants', 'server_ip')
    # ### end Alembic commands ###
