"""Company user & Tenant user assign column

Revision ID: 478dd1f46cc4
Revises: d385668d02a3
Create Date: 2025-06-30 00:05:49.913424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478dd1f46cc4'
down_revision: Union[str, None] = 'd385668d02a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_users', sa.Column('assign', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tenant_users', sa.Column('assign', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_users', 'assign')
    op.drop_column('company_users', 'assign')
    # ### end Alembic commands ###
