"""Adjust column name company acccess

Revision ID: f260d9d87ad0
Revises: 21a652e2cc93
Create Date: 2025-06-13 20:18:24.480508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f260d9d87ad0'
down_revision: Union[str, None] = '21a652e2cc93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_accesses', sa.Column('lexobot_worker_api_key', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_company_accesses_openai_api_key'), table_name='company_accesses')
    op.create_index(op.f('ix_company_accesses_lexobot_worker_api_key'), 'company_accesses', ['lexobot_worker_api_key'], unique=True)
    op.drop_column('company_accesses', 'openai_api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_accesses', sa.Column('openai_api_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_company_accesses_lexobot_worker_api_key'), table_name='company_accesses')
    op.create_index(op.f('ix_company_accesses_openai_api_key'), 'company_accesses', ['openai_api_key'], unique=True)
    op.drop_column('company_accesses', 'lexobot_worker_api_key')
    # ### end Alembic commands ###
