services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lexobot-admin

  api:
    image: backend-admin-image
    container_name: lexobot-api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - lexobot-admin

  frontend:
    image: frontend-admin-image
    container_name: lexobot-admin
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - lexobot-admin

volumes:
  postgres_data:

networks:
  lexobot-admin:
    driver: bridge
