services:
  frontend:
    image: frontend-chat-image
    container_name: lexobot-chat
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - lexobot-network

  gateway:
    image: tenant-gateway-image
    container_name: tenant-gateway
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - ./tenants.json:/app/tenants.json:ro
    networks:
      - lexobot-network

networks:
  lexobot-network:
    driver: bridge
