services:
  frontend:
    image: frontend-chat-image
    container_name: lexobot-chat
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - lexobot-chat

networks:
  lexobot-chat:
    driver: bridge
